config/routes.rb
Rails.application.routes.draw do
  resources :history_records
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history_record.rb
class HistoryRecord < ApplicationRecord

  concerning :FieldDefinitionFeature do
    included do
      FIELDS = [
          :classification_l, :classification_m,
          :filename, :year, :accept_method, :creator,
          :source_1, :source_2, :source_3,
          :accept_date,
          :store_location_shelf_name, :store_location_shelf_id1,
          :store_location_shelf_id2,
          :media_type, :duplicatable, :use_limit,
          :size, :old_maintainer, :misc
      ]
      FIELDS_MAP_SOURCE = FIELDS.map.with_index { |value, index|
        [index+1, value]
      }
      FIELDS_MAP = Hash[FIELDS_MAP_SOURCE]
      store_accessor :data, *FIELDS
    end
  end

  concerning :ImportFeature do
    class_methods do
      def import(file)
        lines = File.open(file).readlines.map { |line| line.strip.split(/\t/) }
        lines.each do |words|
          attrs = map_fields(words)
          HistoryRecord.where(uid: attrs[:uid]).first_or_create(attrs)
        end
      end
      private
      def map_fields(words)
        hash = {}
        words.each_with_index do |value, index|
          key = FIELDS_MAP[index]
          if key.present?
            hash[FIELDS_MAP[index]] = value
          end
        end
        hash[:uid] = words[0] # unique identifier
        hash
      end
    end
  end
  concerning :ImportXlsxFeature do
    class_methods do
      def import_xlsx(file, start_row)
        xlsx = Roo::Excelx.new(file)
        sheet = xlsx.sheet(0)
        sheet.each_row_streaming(offset: start_row) do |row|
          row_s = row.to_a.map { |w| w.blank? ? nil : w.to_s }
          pp row_s
          attrs = map_fields(row_s)
          HistoryRecord.where(uid: attrs[:uid]).first_or_create(attrs)
        end
      end
    end
  end
  concerning :SortFeature do
    included do
      scope :uid_order, -> { order(:uid) }
    end
  end
  concerning :SchemaFeature do
    def num_year
      return nil unless self.year.present?
      self.year.gsub(/年度$/, '').gsub(/\[(.+?)\]/, '\1')
    end

    def schema
      @schema ||= begin
        "tta:#{self.uid} schema:dateCreated:\"#{self.num_year}\""
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/history_records_controller.rb
class HistoryRecordsController < ApplicationController
  before_action :set_history_record, only: [:show, :edit, :update, :destroy]

  # GET /history_records
  # GET /history_records.json
  def index
    @history_records = HistoryRecord.uid_order
  end

  # GET /history_records/1
  # GET /history_records/1.json
  def show
  end

  # GET /history_records/new
  def new
    @history_record = HistoryRecord.new
  end

  # GET /history_records/1/edit
  def edit
  end

  # POST /history_records
  # POST /history_records.json
  def create
    @history_record = HistoryRecord.new(history_record_params)

    respond_to do |format|
      if @history_record.save
        format.html { redirect_to @history_record, notice: 'History record was successfully created.' }
        format.json { render :show, status: :created, location: @history_record }
      else
        format.html { render :new }
        format.json { render json: @history_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /history_records/1
  # PATCH/PUT /history_records/1.json
  def update
    respond_to do |format|
      if @history_record.update(history_record_params)
        format.html { redirect_to @history_record, notice: 'History record was successfully updated.' }
        format.json { render :show, status: :ok, location: @history_record }
      else
        format.html { render :edit }
        format.json { render json: @history_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /history_records/1
  # DELETE /history_records/1.json
  def destroy
    @history_record.destroy
    respond_to do |format|
      format.html { redirect_to history_records_url, notice: 'History record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_history_record
    @history_record = HistoryRecord.find_by(uid: params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def history_record_params
    params.require(:history_record).permit(:uid, :data)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/history_records_helper.rb
module HistoryRecordsHelper
end

app/views/history_records/_form.html.erb
<%= form_with(model: history_record, local: true) do |form| %>
  <% if history_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history_record.errors.count, "error") %> prohibited this history_record from being saved:</h2>

      <ul>
      <% history_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uid %>
    <%= form.text_field :uid, id: :history_record_uid %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data, id: :history_record_data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/history_records/edit.html.erb
<h1>Editing History Record</h1>

<%= render 'form', history_record: @history_record %>

<%= link_to 'Show', @history_record %> |
<%= link_to 'Back', history_records_path %>

app/views/history_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>History Records</h1>

<table class="table">
  <thead>
    <tr>
      <th>Schema</th>
      <th><%= t('activerecord.attributes.history_record.uid') %></th>
      <% HistoryRecord::FIELDS.each do |field| %>
        <th><%= t("activerecord.attributes.history_record.#{field}") %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @history_records.each do |history_record| %>
      <tr>
        <td><%= history_record.schema %></td>
        <td><%= link_to history_record.uid, history_record_path(history_record.uid) %></td>
        <% HistoryRecord::FIELDS.each do |field| %>
          <td><%= history_record.send(field) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History Record', new_history_record_path %>

app/views/history_records/new.html.erb
<h1>New History Record</h1>

<%= render 'form', history_record: @history_record %>

<%= link_to 'Back', history_records_path %>

app/views/history_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.history_record.uid') %>:</strong>
  <%= @history_record.uid %>
</p>

<p>
  <strong>schema</strong>
  <%= @history_record.schema %>
</p>
<% HistoryRecord::FIELDS.each do |field| %>
    <p>
      <strong><%= t("activerecord.attributes.history_record.#{field}") %>:</strong>
      <%= @history_record.send(field) %>
    </p>
<% end %>

<%= link_to 'Back', history_records_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hirec</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>